### ISSUE TITLE
How does it know which release to update?

### ISSUE THREAD

**Issue by pmalon** [tubone24/update_release#382]
Since the name of the action is "update_release" then I was expecting to see the release Id as one of the inputs which seems not to be the case, so I wonder how does the action know which release to update?

**Comment by tubone24** [comment]
@pmalon 
Sorry it took so long to get back to you!
The releaseId is created by creating a GitHub Actions that triggers the release to be turned off from GitHub Releases and get the releaseId from the tag.

https://github.com/tubone24/update_release/blob/master/src/update-release.ts#L27


The purpose of this GitHub Actions is to update the Release Note when a Release is created from GitHub Releases. Therefore, it has a function to operate on a specific release by passing the releaseId to the input environment variable as a hidden element instead of input.

https://github.com/tubone24/update_release/blob/master/src/update-release.ts#L18

**Comment by pmalon** [comment]
thank you @tubone24 🙇 I was able to achieve my goal (append deployment time information for a given release) by specifying TAG_NAME env variable
